// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "myAnim0":
            case "anim2":return [img`
...................
..........f...f....
..........3f.f3....
..........fffff....
..........f7f7f....
..........ff3ff....
...ffffffffffff....
...ffffffff........
f.fffffffff........
.f.ffffffff........
...fff...fff.......
...f.ff..f.ff......
...f..f..f..f......
...3...1.3...1.....
...................
...................
`, img`
...................
..........f...f....
..........3f.f3....
..........fffff....
..........f7f7f....
..........ff3ff....
...ffffffffffff....
...ffffffff........
fffffffffff........
...ffffffff........
...ff....ff........
...ff....ff........
...ff....ff........
...31....31........
...................
...................
`, img`
...................
..........f...f....
..........3f.f3....
..........fffff....
..........f7f7f....
..........ff3ff....
f..ffffffffffff....
.f.ffffffff........
..fffffffff........
...ffffffff........
...ff....ff........
..f.f...f.f........
.f..f..f..f........
.3..1..3..1........
...................
...................
`, img`
...................
..........f...f....
..........3f.f3....
..........fffff....
..........f7f7f....
..........ff3ff....
f..ffffffffffff....
.f.ffffffff........
..fffffffff........
...ffffffff........
...ff....ff........
...ff....ff........
...ff....ff........
...31....31........
...................
...................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
