/**
 */
// jumping & gravity
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (kittyCat.isHittingTile(CollisionDirection.Bottom)) {
        kittyCat.vy = -90
    }
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.tilePath5, function (sprite, location) {
    game.showLongText("Hello Player you are now a cat and playing the tutorial of this game Use A and D to move around and when you approach a wall you can climb it just Jump onto it using Spacebar and hit W and D to start climbing up this game is pretty simple to you're probably going to master the controls soon have fun ill teleport you onto the next platform now.", DialogLayout.Bottom)
    tiles.placeOnTile(kittyCat, tiles.getTileLocation(19, 7))
})
let kittyCat: Sprite = null
let isClimbling = false
// tilemap
scene.setBackgroundColor(13)
tiles.setCurrentTilemap(tilemap`level1`)
game.showLongText("Welcome to kitty parkour use A and D to move around Ill run you through the tutorial ", DialogLayout.Bottom)
// sprite code
kittyCat = sprites.create(img`
    ...................
    ...................
    ...................
    ............f...f..
    ............3f.f3..
    ............fffff..
    ............f7f7f..
    ............ff3ff..
    ....fffffffffffff..
    .ff.fffffffff......
    ...ffffffffff......
    ....fffffffff......
    ....ff.....ff......
    ....ff.....ff......
    ....ff.....ff......
    ....31.....31......
    `, SpriteKind.Player)
tiles.placeOnTile(kittyCat, tiles.getTileLocation(9, 9))
controller.moveSprite(kittyCat, 100, 0)
scene.cameraFollowSprite(kittyCat)
kittyCat.ay = 100
// scaling CollisionDirection
forever(function () {
    if (kittyCat.isHittingTile(CollisionDirection.Right)) {
        controller.moveSprite(kittyCat, 0, 30)
        isClimbling = true
        kittyCat.ay = 0
    } else if (!(kittyCat.isHittingTile(CollisionDirection.Right))) {
        controller.moveSprite(kittyCat, 100, 0)
        isClimbling = false
        kittyCat.ay = 100
    }
})
forever(function () {
    if (controller.right.isPressed()) {
        animation.runImageAnimation(
        kittyCat,
        assets.animation`myAnim0`,
        200,
        true
        )
    } else if (!(controller.right.isPressed())) {
        animation.stopAnimation(animation.AnimationTypes.All, kittyCat)
    }
})
forever(function () {
    if (isClimbling == true) {
        animation.stopAnimation(animation.AnimationTypes.All, kittyCat)
        kittyCat.setImage(img`
            ................
            ................
            ................
            .f3ffff.........
            ..ff7ff.........
            ...ff3f.........
            ..ff7ff.........
            .f3ffffffffff1..
            ......fffffff3..
            ......ffff......
            ......ffff......
            ......ffff......
            ......ffff......
            ......ffff......
            ......fffffff1..
            ......fffffff3..
            ........f.......
            .......f........
            .......f........
            `)
    }
})
forever(function () {
    if (isClimbling == false) {
        kittyCat.setImage(img`
            ...................
            ...........f...f...
            ...........3f.f3...
            ...........fffff...
            ...........f7f7f...
            ...........ff3ff...
            ...fffffffffffff...
            ff.fffffffff.......
            ..ffffffffff.......
            ...fffffffff.......
            ...ff.....ff.......
            ...ff.....ff.......
            ...ff.....ff.......
            ...31.....31.......
            ...................
            ...................
            `)
    }
})
